### ISSUE TITLE
Mental Health Checkup

### ISSUE THREAD

**Issue by DeadlySurgeon** [Xe/ircmon#1]
I found a bug with a developer working in this repository and I think that she needs to seek a therapist. I cannot imagine what could have drove the developer to such madness to use Perl nevertheless I hope for a swift recovery from the anguish. One could only imagine the pain she must be going through.
  
  
  
Get well soon,
The Surgeon

**Comment by Xe** [comment]
Working as intended.

**Comment by DeadlySurgeon** [comment]
> Working as intended.

![image](https://user-images.githubusercontent.com/60354262/119246557-25bb3f80-bb48-11eb-9dee-7e79afdae697.png)
